name: Rust
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  PKG_CONFIG_ALLOW_CROSS: 1  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gmiam/rust-musl-action@master
    - name: Build-musl
      run: pwd && ls && env | grep PKG && rustup target add x86_64-unknown-linux-musl && cargo build --target $BUILD_TARGET --release
