name: Rust-static-build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  OPENSSL_LIB_DIR: /usr/local/ssl/lib 
  OPENSSL_INCLUDE_DIR: /usr/local/ssl/include
  OPENSSL_STATIC: 1
  PKG_CONFIG_ALLOW_CROSS: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build-musl
      uses: gmiam/rust-musl-action@master
      with:
        args: ls -a && cargo build --target $BUILD_TARGET --release
      #run: pwd  && ls /.cargo/config && ls /usr && ls /usr/local && ls && env | grep PKG && env | grep OPENSSL && rustup target add x86_64-unknown-linux-musl && cargo build --target $BUILD_TARGET --release
